---
- name: test play
  hosts: localhost
  gather_facts: no
  tasks:

    - name: 
      set_facts: 
        version_admin: '{{version}}'
      when: version_admin is not defined

    - debug:
        var: version_admin
