---
- name: test play
  hosts: localhost
  gather_facts: no
  tasks:
    - name: one
      version_admin_new: '{{version}}'
      when: version_admin == ''

    - name: two
      version_admin_new: '{{version_admin}}'
      when: version_admin != ''

    - debug: var=version_admin_new
