---
- name: test play
  hosts: localhost
  gather_facts: no
  tasks:
    - name: 
      set_fact: 
        version_admin: '{{version}}'
      when: version_admin == ''

    - debug:
        var: ansible_facts.version_admin
